---
title: "ch1-5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}

library(ggplot2)
library(GGally)
library(HSAUR2)
library(MVA)
library(aplpack)
library(dplyr)

```

```{r ch1-5-1-ggpairs}
data("USairpollution")
ggpairs(USairpollution,
        lower = list(continuous = wrap("smooth", alpha = 0.3)),
        diag = list(discrete="barDiag", 
                    continuous = wrap("densityDiag", alpha = 0.5 )))
str(USairpollution)

```

```{r ch1-5-1-stars}

stars(USairpollution, main = "Star plot for USairpollution",
      nrow = 6, key.loc = c(- 1, 12), cex = 0.8, lwd = 2)

```

```{r ch1-5-2-facess}

faces(USairpollution, main = "Chernoff faces for USairpollution",
      nrow.plot = 6, face.type = 1, cex = 1.5)

```

```{r ch1-5-2}

x <- USairpollution %>% select(temp, wind)
bvbox(x, xlab = "temp", ylab = "wind",
      main = "Bivariate boxplot for USairpollution")
text(x, labels = row.names(x), cex=0.7)

```

```{r ch1-5-3}
plot(popul ~ manu, data = USairpollution, pch = 9)
with(USairpollution, symbols(manu, popul, circles = SO2, 
                             inches = 0.5, add = TRUE))
title(main = "Bubble plot for USairpollution")

summary(lm(SO2 ~ manu + popul, data = USairpollution))
```


https://rpubs.com/nevret/424576
