---
title: "ch2-1"
author: "Harry Woo"
date: '2020 5 19 '
output: html_document

<style> body .main-container { max-width: 1200px; } </style> 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set-options, echo=FALSE, cache=FALSE} 
options(width = 1200) 
``` 
 

```{r load-packages}

library(ggplot2)
library(GGally)
library(HSAUR2)
library(MVA)
library(aplpack)
library(dplyr)
library(ade4)
library(pander)

```

```{r ch2-1-1}

data(deug)
data <- deug$tab
summary(data)

```


```{r ch2-1-2}

round(cor(data), 2)
ggpairs(data, lower = list(continuous = GGally::wrap("smooth", alpha = 0.3, size = 0.1)))

```

```{r ch2-1-3}

data_pca <- princomp(data, cor = TRUE, scores = TRUE)
data_pca$sdev^2 #고유근

summary(data_pca)

data_pca$loadings

screeplot(data_pca, type = "lines", pch = 19, main = "Scree Plot")

```

```{r ch2-1-4}


```

```{r ch2-1-5}

screeplot(data_pca, type = "lines", pch = 19, main = "Scree Plot")

```

```{r ch2-1-6}

print(data_pca$loadings[, 1:3], digits = 3)

```

```{r ch2-1-7}

biplot(data_pca, cex = 0.7, col = c("red", "blue"), main = "Biplot")

```