---
title: "ch4-2"
author: "Harry Woo"
date: '2020 6 16 '
output:
  html_document: default
  word_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
rm(list = ls())
library(dplyr)
library(pls)
library(ggplot2)
library(GGally)
library(gt)
```

```{r}

data(iris)
str(iris)
head(iris) %>% gt()

```

# 각 변수의 표준화한 값
```{r}

z_iris <- cbind(stdize(as.matrix(iris[-5])), iris[5])
head(z_iris) %>% gt()

```

# K-평균 군집분석방법을 이용하여 3개 군집에 대한 군집분석 실시
```{r}

set.seed(2992)
km_cluster <- kmeans(z_iris[-5], 3)
km_cluster

```

# 군집 결과를 소속군집 산점도로 표현
```{r}

pairs(z_iris, col = km_cluster$cluster, pch = 16)
ggpairs(z_iris, aes(colour = as.factor(km_cluster$cluster)))

```

# K-평균 군집분석의 군집결과와 붓꽃 데이터에 주어져 있는 종류와의 분할표 통해 군집분석의 성능 평가
```{r}

z_iris2 <- cbind(z_iris, fit = km_cluster$cluster)
confu_mat <- table(z_iris2$Species, z_iris2$fit)
confu_mat

```

# 성능 평가를 위하여 fit 결과를 분류
```{r}
z_iris3 <- z_iris2 %>% 
  mutate(fit = ifelse(fit == 2, "setosa", ifelse(fit == 3, "versicolor", "virginica")))
confu_mat2 <- table(z_iris3$Species, z_iris3$fit)
confu_mat2

# 오분류율 계산
error <- 1 - sum(diag(confu_mat2))/sum(confu_mat2)
error
1 - error
```

오분류율 16.7%, 정분류율은 83.3%, 특히 Setosa는 완벽히 분류되었음