---
title: "ch7-2"
author: "Harry Woo"
date: '2020 6 16 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(MASS)
library(klaR)
library(dplyr)
library(gt)
```

```{r}
city <- read.csv("ex7-2.csv")
head(city) %>% gt()
summary(city)
str(city)
```

```{r}
city_lda <- lda(type ~ ., data = city)
city_lda #그룹이 2개이므로 1개 선형판별함수 출력
```

```{r}
pred_lda <- predict(city_lda, newdata = city)
names(pred_lda)
head(pred_lda$class)
head(pred_lda$posterior) %>% gt()
head(pred_lda$x) %>% gt()
```

```{r}
confu_mat <- table(city$type, pred_lda$class)
confu_mat

error <- 1 - sum(diag(confu_mat))/sum(confu_mat)
error
```

# 변수선택 가능? 안되는데? 안되는게 정상이라고.
# city_forward <- greedy.wilks(type ~ ., data = city, niveau = 0.01)

```{r}
# 분류함수
source("classfunc.r")
X <- city[, -1]
classfunc_result <- classfunc.lda(X, city$type)
classfunc_result$class.func %>% gt()
classfunc_result

X2 <- X %>% 
  mutate(ind = -12.7537645 + 0.3272460 * population + 0.5556657 * pollution,
         mer = -12.702302 + 0.365933 * population + 0.526113 * pollution) %>% 
  mutate(type = city$type, type2 = ifelse(ind > mer, "ind", "mer"))

head(X2) %>% gt()

confu_mat2 <- table(X2$type, X2$type2)
confu_mat2

error <- 1 - sum(diag(confu_mat2))/sum(confu_mat2)
error
```