---
title: "ch8-6"
author: "Harry Woo"
date: '2020 6 16 '
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
rm(list = ls())

library(MASS) # for menarche
library(dplyr)
library(ggplot2)
library(gt)
library(RWeka)
library(caret)

```

```{r}
data(menarche)
head(menarche) %>% gt()
```

```{r}
mnc_plot <- ggplot(data = menarche, aes(x = Age, y = Menarche/Total)) +
  geom_point(pch = 19)
mnc_plot
# S-shape : 로지스틱 회귀모형 적합 타당
```

```{r}
mnc_glm <- glm(cbind(Menarche, Total - Menarche) ~ Age, family = binomial, data = menarche)
summary(mnc_glm)
# Age 유의

exp(mnc_glm$coefficients["Age"])

1 - pchisq(mnc_glm$deviance, mnc_glm$df.residual)
```

```{r}
mnc_glm$fitted

mnc_plot + geom_line(aes(x = Age, y = mnc_glm$fitted), lwd = 1.2, colour = "royalblue") +
  ggtitle(label = "Menarche Data with Fitted Logistic Regression Line")

```

```{r}

prediction <- ifelse(predict(mnc_glm, menarche, type = "response") > 0.5, TRUE, FALSE)
table(as.numeric(prediction), as.numeric(as.logical(mnc_glm$y)))

menarche2 <- menarche %>% 
  mutate(ratio = ifelse(Menarche/Total < 0.5, "No", "Yes"), fit = prediction)
confm_mnc <- table(menarche2$ratio, menarche2$fit)

error <- 1 - sum(diag(confm_mnc))/sum(confm_mnc)
error

mnc_glm$y == menarche$Menarche/menarche$Total

```