---
title: "ch9-2"
author: "Harry Woo"
date: '2020 6 16 '
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Package Loading
rm(list = ls())
library(dplyr)
library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
library(gt)

# Data Loading
data(iris)
head(iris)

# 전처리
firis <- iris %>% rename(SL = Sepal.Length, SW = Sepal.Width, 
                         PL = Petal.Length, PW = Petal.Width, SP = Species) %>% 
  mutate(SP = factor(SP, labels = c("st","vc","vg")))
head(firis) %>% gt()

```

```{r}
# rpart 함수를 이용하여 나무모형을 수행한 후, 나무모형의 도형화 결과를 보이고 결과를 해석하시오. 
# 나무모형을 이용하여 분류한 결과와  원래 그룹과의 분류표를 구하고, 오분류율을 구하시오. 

tree <- rpart(SP ~ ., data = firis)
tree
```

```{r}
plot(tree, uniform = TRUE, compress = TRUE, margin = 0.1)
text(tree, use.n = TRUE, col = "blue")

fancyRpartPlot(tree, main = "rpart trees of iris \n", caption = "", type = 1)

```

```{r}
prediction <- predict(tree, newdata = firis, type = "class")

confu_mat <- table(firis$SP, prediction, dnn = c("Actual", "Predicted"))
confu_mat

error <- 1 - sum(diag(confu_mat)) / sum(confu_mat)
error

summary(tree)
```

```{r}
# 정지규칙에서 가지를 나누는 최소 자료의 수를 5로 하여 나무모형을 수행하고 앞의 (1)의 결과와 비교하시오

my_control <- rpart.control(minsplit = 5)
tree2 <- rpart(SP ~ ., data = firis, method = "class", control = my_control)
tree2

```

```{r}
plot(tree2, uniform = TRUE, compress = TRUE, margin = 0.1)
text(tree2, use.n = TRUE, col = "blue")

fancyRpartPlot(tree2, main = "rpart trees of iris \n", caption = "", type = 1)

```

```{r}

prediction2 <- predict(tree2, newdata = firis, type = "class")

confu_mat2 <- table(firis$SP, prediction2, dnn = c("Actual", "Predicted"))
confu_mat2

error2 <- 1 - sum(diag(confu_mat2)) / sum(confu_mat2)
error2

summary(tree2)
```

# 오분류율이 개선되었다.
